In [ ]:
# 분류 4가지(RF, DT, SVM, LR)

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:/Users/seongmun/AiStudy/AI_Study/data/diabetes.csv', index_col=0)
df

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
Pregnancies                                                         
6                148             72             35        0  33.6   
1                 85             66             29        0  26.6   
8                183             64              0        0  23.3   
1                 89             66             23       94  28.1   
0                137             40             35      168  43.1   
...              ...            ...            ...      ...   ...   
10               101             76             48      180  32.9   
2                122             70             27        0  36.8   
5                121             72             23      112  26.2   
1                126             60              0        0  30.1   
1                 93             70             31        0  30.4   

             DiabetesPedigreeFunction  Age  Outcome  
Pregnancies                                          
6                               0.627   50        1  
1                               0.351   31        0  
8                               0.672   32        1  
1                               0.167   21        0  
0                               2.288   33        1  
...                               ...  ...      ...  
10                              0.171   63        0  
2                               0.340   27        0  
5                               0.245   30        0  
1                               0.349   47        1  
1                               0.315   23        0  

[768 rows x 8 columns]

In [3]:
y = df['Outcome']
y

Pregnancies
6     1
1     0
8     1
1     0
0     1
     ..
10    0
2     0
5     0
1     1
1     0
Name: Outcome, Length: 768, dtype: int64

In [6]:
x = df
x.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
Pregnancies                                                         
6                148             72             35        0  33.6   
1                 85             66             29        0  26.6   
8                183             64              0        0  23.3   
1                 89             66             23       94  28.1   
0                137             40             35      168  43.1   

             DiabetesPedigreeFunction  Age  Outcome  
Pregnancies                                          
6                               0.627   50        1  
1                               0.351   31        0  
8                               0.672   32        1  
1                               0.167   21        0  
0                               2.288   33        1

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
# x에는 입력데이터, y에는 타깃 데이터(모델이 예측하려는 실제 정답값)
x_train.shape, x_test.shape, y_train.shape, y_test.shape
# x_train : 훈련 데이터의 입력 특성
# y_train : 훈련 데이터의 정답(타깃 데이터 or 레이블)
# x_test : 예측 데이터의 입력 특성
# y_test : 예측 데이터의 정답(타깃 데이터 or 레이블)
# x : (입력 데이터 갯수, feature 갯수)
# y : (타깃 데이터 갯수)

((576, 8), (192, 8), (576,), (192,))

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [9]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
1.0
[[130   0]
 [  0  62]]


In [ ]:
# Outcome은 0,1 두가지 클래스가 있으므로, 2x2행렬이 나온다.

In [10]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
1.0
[[130   0]
 [  0  62]]


In [11]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
1.0
[[130   0]
 [  0  62]]


C:\Users\seongmun\anaconda3\envs\test01\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# 수렴 실패

In [12]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.7760416666666666
[[119  11]
 [ 32  30]]
